import { buildBudgetEstimatePdf, buildBudgetSheetPdf, buildPdfDocument, clampText, formatCurrency, normalizeDate, safeArray } from "../utils.js";
import { generateProposalNarrative } from "./ai.js";

const buildReportParagraphs = (payload) => {
  const attendeeLine = payload.totalAttendees
    ? `${payload.totalAttendees} attendees participated`
    : "attendance details will be finalized by the organizing team";
  const budgetLine = payload.actualSpend
    ? `The final spend was ${formatCurrency(payload.actualSpend)} against an approved estimate of ${formatCurrency(payload.totalBudget || payload.actualSpend)}.`
    : "The final financial reconciliation is in progress.";

  return [
    `This report summarizes the event "${payload.eventTitle}" organized by the ${payload.clubName} on ${normalizeDate(payload.eventDate)} at ${payload.venue || "the designated venue"}.`,
    `Based on the inputs submitted, ${attendeeLine}. The event focus included ${clampText(payload.eventSummary || "knowledge sharing, engagement, and structured execution")}.`,
    `${budgetLine} The organizing team tracked the event through planned activities, participant engagement, and operational checkpoints.`,
    `Major outcomes include ${clampText(payload.outcomes || "successful execution, audience participation, and completion of the planned agenda")}. Supporting photographs and highlights have been included separately for archival and review purposes.`,
  ];
};

export const generateProposalDocument = async (payload) => {
  const proposalNarrative = await generateProposalNarrative(payload);
  const pdfBuffer = await buildPdfDocument({
    title: "Event Proposal",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Proposal",
    date: payload.date || payload.eventDate,
    subject: payload.subject || `Proposal for ${payload.eventTitle || "Event"}`,
    addressedTo: payload.authorityName,
    clubName: payload.clubName,
    bodyParagraphs: proposalNarrative.paragraphs,
    highlights: safeArray(payload.keyPoints),
    footerText: "Generated by DocuPrint Proposal Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
    signatories: safeArray(payload.signatories),
  });

  return {
    fileName: `${(payload.eventTitle || "event-proposal").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventTitle,
      clubName: payload.clubName,
      authorityName: payload.authorityName,
      estimatedBudget: payload.budget ? formatCurrency(payload.budget) : null,
      narrativeSource: proposalNarrative.source,
    },
    narrative: proposalNarrative.paragraphs,
    pdfBuffer,
  };
};

export const generateReportDocument = async (payload) => {
  const analytics = [
    payload.totalAttendees ? `Participants recorded: ${payload.totalAttendees}` : null,
    payload.feedbackScore ? `Average feedback score: ${payload.feedbackScore}/10` : null,
    payload.totalBudget ? `Approved budget: ${formatCurrency(payload.totalBudget)}` : null,
    payload.actualSpend ? `Actual spend: ${formatCurrency(payload.actualSpend)}` : null,
  ].filter(Boolean);

  const pdfBuffer = await buildPdfDocument({
    title: "Event Report",
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    documentLabel: "Event Report",
    date: payload.date || payload.eventDate,
    subject: payload.subject || `Report for ${payload.eventTitle || "Event"}`,
    addressedTo: payload.authorityName,
    clubName: payload.clubName,
    bodyParagraphs: buildReportParagraphs(payload),
    highlights: safeArray(payload.keyHighlights),
    analytics,
    footerText: "Generated by DocuPrint Reporting Engine",
    collegeLogo: payload.collegeLogo,
    clubLogo: payload.clubLogo,
    collegeAcronym: payload.collegeAcronym,
    clubAcronym: payload.clubAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    clubBrandColor: payload.clubBrandColor,
  });

  return {
    fileName: `${(payload.eventTitle || "event-report").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      eventTitle: payload.eventTitle,
      totalAttendees: payload.totalAttendees || null,
      actualSpend: payload.actualSpend ? formatCurrency(payload.actualSpend) : null,
      keyHighlights: safeArray(payload.keyHighlights),
    },
    pdfBuffer,
  };
};

export const generateBudgetReportDocument = async (payload) => {
  const records = safeArray(payload.records);
  const resolvedTitle =
    payload.title ||
    (records.length === 1 ? `${records[0].title} Budget Report` : "College Budget Expenditure Report");

  const pdfBuffer = await buildBudgetSheetPdf({
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    date: payload.date,
    title: resolvedTitle,
    collegeLogo: payload.collegeLogo,
    collegeAcronym: payload.collegeAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    records,
  });

  return {
    fileName: `${resolvedTitle.replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      title: resolvedTitle,
      records: records.length,
      generatedOn: normalizeDate(payload.date),
    },
    pdfBuffer,
  };
};

export const generateBudgetEstimationDocument = async (payload) => {
  const pdfBuffer = await buildBudgetEstimatePdf({
    collegeName: payload.collegeName,
    collegeAddress: payload.collegeAddress,
    date: payload.date,
    title: payload.title || "Budget Estimation Report",
    collegeLogo: payload.collegeLogo,
    collegeAcronym: payload.collegeAcronym,
    collegeBrandColor: payload.collegeBrandColor,
    eventType: payload.eventType,
    attendees: payload.attendees,
    summary: payload.summary,
    estimatedTotalFormatted: payload.estimatedTotalFormatted,
    breakdown: safeArray(payload.breakdown),
    recommendations: safeArray(payload.recommendations),
  });

  return {
    fileName: `${(payload.title || "budget-estimation-report").replace(/\s+/g, "-").toLowerCase()}.pdf`,
    summary: {
      title: payload.title || "Budget Estimation Report",
      eventType: payload.eventType || null,
      generatedOn: normalizeDate(payload.date),
    },
    pdfBuffer,
  };
};
