import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Download, BarChart3, PieChart, TrendingUp, Calendar } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart as RPieChart,
  Pie,
  Cell,
  LineChart,
  Line,
  Legend,
} from "recharts";

interface ReportData {
  eventName: string;
  date: string;
  totalAttendees: string;
  totalBudget: string;
  actualSpend: string;
  feedback: string;
}

const emptyReport: ReportData = {
  eventName: "",
  date: "",
  totalAttendees: "",
  totalBudget: "",
  actualSpend: "",
  feedback: "",
};

const CHART_COLORS = [
  "hsl(265, 85%, 55%)",
  "hsl(25, 95%, 55%)",
  "hsl(165, 70%, 45%)",
  "hsl(0, 84%, 60%)",
  "hsl(45, 90%, 50%)",
];

const ReportGenerator = () => {
  const [data, setData] = useState<ReportData>(emptyReport);

  const update = (field: keyof ReportData, value: string) => {
    setData((prev) => ({ ...prev, [field]: value }));
  };

  const attendees = parseInt(data.totalAttendees) || 0;
  const budget = parseInt(data.totalBudget) || 0;
  const spent = parseInt(data.actualSpend) || 0;
  const remaining = Math.max(budget - spent, 0);
  const feedbackScore = parseFloat(data.feedback) || 0;

  const budgetData = useMemo(
    () => [
      { name: "Venue", amount: Math.round(spent * 0.35) },
      { name: "Catering", amount: Math.round(spent * 0.25) },
      { name: "Marketing", amount: Math.round(spent * 0.15) },
      { name: "Equipment", amount: Math.round(spent * 0.15) },
      { name: "Misc", amount: Math.round(spent * 0.1) },
    ],
    [spent]
  );

  const pieData = useMemo(
    () => [
      { name: "Spent", value: spent },
      { name: "Remaining", value: remaining },
    ],
    [spent, remaining]
  );

  const attendanceTrend = useMemo(() => {
    const base = Math.max(attendees * 0.6, 10);
    return [
      { hour: "9 AM", count: Math.round(base * 0.3) },
      { hour: "10 AM", count: Math.round(base * 0.6) },
      { hour: "11 AM", count: Math.round(base * 0.85) },
      { hour: "12 PM", count: Math.round(base) },
      { hour: "1 PM", count: Math.round(base * 0.9) },
      { hour: "2 PM", count: Math.round(base * 0.95) },
      { hour: "3 PM", count: Math.round(base * 0.75) },
      { hour: "4 PM", count: Math.round(base * 0.5) },
    ];
  }, [attendees]);

  const feedbackBreakdown = useMemo(() => {
    const s = feedbackScore;
    return [
      { label: "Excellent", value: Math.round(Math.max(s * 10, 5)) },
      { label: "Good", value: Math.round(Math.max((10 - s) * 5, 10)) },
      { label: "Average", value: Math.round(Math.max((10 - s) * 3, 3)) },
      { label: "Poor", value: Math.round(Math.max((10 - s) * 1, 1)) },
    ];
  }, [feedbackScore]);

  const handleExport = () => {
    const content = `
EVENT REPORT
============
Event: ${data.eventName}
Date: ${data.date}
Total Attendees: ${attendees}
Budget: ₹${budget}
Actual Spend: ₹${spent}
Remaining: ₹${remaining}
Feedback Score: ${feedbackScore}/10

BUDGET BREAKDOWN
${budgetData.map((d) => `  ${d.name}: ₹${d.amount}`).join("\n")}

---
Generated by DocuPrint
    `.trim();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.eventName || "report"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen p-6 md:p-10">
      {/* Header */}
      <motion.header
        className="flex items-center justify-between mb-8"
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
      >
        <div className="flex items-center gap-4">
          <a href="/dashboard" className="brutal-btn-outline py-2 px-3 flex items-center gap-1 text-xs">
            <ArrowLeft className="w-4 h-4" strokeWidth={3} />
            Back
          </a>
          <h1 className="text-xl font-bold uppercase tracking-tight">Report Generator</h1>
        </div>
        <button onClick={handleExport} className="brutal-btn-primary flex items-center gap-2 py-2">
          <Download className="w-4 h-4" strokeWidth={3} />
          Export
        </button>
      </motion.header>

      {/* Input Form */}
      <motion.div
        className="brutal-card max-w-4xl mb-8"
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.1 }}
      >
        <div className="brutal-border bg-muted/30 p-1.5 inline-block mb-4">
          <span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Event Details</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 block">Event Name</label>
            <input className="brutal-input" placeholder="Annual Tech Symposium" value={data.eventName} onChange={(e) => update("eventName", e.target.value)} />
          </div>
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5" /> Date
            </label>
            <input type="date" className="brutal-input" value={data.date} onChange={(e) => update("date", e.target.value)} />
          </div>
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 block">Total Attendees</label>
            <input type="number" className="brutal-input" placeholder="250" value={data.totalAttendees} onChange={(e) => update("totalAttendees", e.target.value)} />
          </div>
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 block">Budget (₹)</label>
            <input type="number" className="brutal-input" placeholder="50000" value={data.totalBudget} onChange={(e) => update("totalBudget", e.target.value)} />
          </div>
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 block">Actual Spend (₹)</label>
            <input type="number" className="brutal-input" placeholder="42000" value={data.actualSpend} onChange={(e) => update("actualSpend", e.target.value)} />
          </div>
          <div>
            <label className="font-bold text-xs uppercase tracking-wider mb-1.5 block">Feedback Score (1-10)</label>
            <input type="number" min="1" max="10" step="0.1" className="brutal-input" placeholder="8.5" value={data.feedback} onChange={(e) => update("feedback", e.target.value)} />
          </div>
        </div>
      </motion.div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 max-w-4xl">
        {/* Budget Breakdown Bar Chart */}
        <motion.div
          className="brutal-card"
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.2 }}
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="w-7 h-7 bg-primary brutal-border flex items-center justify-center">
              <BarChart3 className="w-4 h-4 text-primary-foreground" strokeWidth={2.5} />
            </div>
            <h3 className="font-bold uppercase text-sm">Budget Breakdown</h3>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={budgetData}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(0,0%,0%,0.1)" />
                <XAxis dataKey="name" tick={{ fontSize: 11, fontFamily: "Space Mono" }} />
                <YAxis tick={{ fontSize: 11, fontFamily: "Space Mono" }} />
                <Tooltip
                  contentStyle={{
                    border: "2px solid hsl(0,0%,0%)",
                    borderRadius: 0,
                    boxShadow: "4px 4px 0px hsl(0,0%,0%)",
                    fontFamily: "Space Mono",
                    fontSize: 12,
                  }}
                  formatter={(value: number) => [`₹${value}`, "Amount"]}
                />
                <Bar dataKey="amount" radius={0}>
                  {budgetData.map((_, i) => (
                    <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} stroke="hsl(0,0%,0%)" strokeWidth={2} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Budget Pie */}
        <motion.div
          className="brutal-card"
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.3 }}
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="w-7 h-7 bg-secondary brutal-border flex items-center justify-center">
              <PieChart className="w-4 h-4 text-secondary-foreground" strokeWidth={2.5} />
            </div>
            <h3 className="font-bold uppercase text-sm">Spent vs Remaining</h3>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <RPieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={50}
                  outerRadius={80}
                  dataKey="value"
                  stroke="hsl(0,0%,0%)"
                  strokeWidth={2}
                  label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                >
                  <Cell fill="hsl(265, 85%, 55%)" />
                  <Cell fill="hsl(165, 70%, 45%)" />
                </Pie>
                <Tooltip
                  contentStyle={{
                    border: "2px solid hsl(0,0%,0%)",
                    borderRadius: 0,
                    boxShadow: "4px 4px 0px hsl(0,0%,0%)",
                    fontFamily: "Space Mono",
                    fontSize: 12,
                  }}
                  formatter={(value: number) => [`₹${value}`, ""]}
                />
              </RPieChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Attendance Trend */}
        <motion.div
          className="brutal-card"
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.4 }}
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="w-7 h-7 bg-accent brutal-border flex items-center justify-center">
              <TrendingUp className="w-4 h-4 text-accent-foreground" strokeWidth={2.5} />
            </div>
            <h3 className="font-bold uppercase text-sm">Attendance Trend</h3>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={attendanceTrend}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(0,0%,0%,0.1)" />
                <XAxis dataKey="hour" tick={{ fontSize: 11, fontFamily: "Space Mono" }} />
                <YAxis tick={{ fontSize: 11, fontFamily: "Space Mono" }} />
                <Tooltip
                  contentStyle={{
                    border: "2px solid hsl(0,0%,0%)",
                    borderRadius: 0,
                    boxShadow: "4px 4px 0px hsl(0,0%,0%)",
                    fontFamily: "Space Mono",
                    fontSize: 12,
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="count"
                  stroke="hsl(265, 85%, 55%)"
                  strokeWidth={3}
                  dot={{ fill: "hsl(25, 95%, 55%)", stroke: "hsl(0,0%,0%)", strokeWidth: 2, r: 5 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* Feedback Breakdown */}
        <motion.div
          className="brutal-card"
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.5 }}
        >
          <div className="flex items-center gap-2 mb-4">
            <div className="w-7 h-7 bg-primary brutal-border flex items-center justify-center">
              <BarChart3 className="w-4 h-4 text-primary-foreground" strokeWidth={2.5} />
            </div>
            <h3 className="font-bold uppercase text-sm">Feedback Distribution</h3>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={feedbackBreakdown} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(0,0%,0%,0.1)" />
                <XAxis type="number" tick={{ fontSize: 11, fontFamily: "Space Mono" }} />
                <YAxis type="category" dataKey="label" tick={{ fontSize: 11, fontFamily: "Space Mono" }} width={70} />
                <Tooltip
                  contentStyle={{
                    border: "2px solid hsl(0,0%,0%)",
                    borderRadius: 0,
                    boxShadow: "4px 4px 0px hsl(0,0%,0%)",
                    fontFamily: "Space Mono",
                    fontSize: 12,
                  }}
                />
                <Bar dataKey="value" radius={0}>
                  {feedbackBreakdown.map((_, i) => (
                    <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} stroke="hsl(0,0%,0%)" strokeWidth={2} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </div>

      {/* Summary Stats */}
      {(attendees > 0 || budget > 0) && (
        <motion.div
          className="grid grid-cols-2 sm:grid-cols-4 gap-4 max-w-4xl mt-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
        >
          {[
            { label: "Attendees", value: attendees.toString(), color: "bg-primary" },
            { label: "Budget", value: `₹${budget.toLocaleString()}`, color: "bg-secondary" },
            { label: "Spent", value: `₹${spent.toLocaleString()}`, color: "bg-accent" },
            { label: "Feedback", value: `${feedbackScore}/10`, color: "bg-primary" },
          ].map((stat) => (
            <div key={stat.label} className="brutal-card !p-4 text-center">
              <div className={`w-3 h-3 ${stat.color} brutal-border mx-auto mb-2`} />
              <p className="font-mono text-xs text-muted-foreground uppercase">{stat.label}</p>
              <p className="font-bold text-xl mt-1">{stat.value}</p>
            </div>
          ))}
        </motion.div>
      )}
    </div>
  );
};

export default ReportGenerator;
